name: Gradient Boosting Notebook Automation

on:
  push:
    branches:
      - main
    paths:
      - 'notebooks/training_gradient_boosting.ipynb'

jobs:

  train_gradient_boosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            source ~/.bashrc
            cd /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator
            conda activate /home/e19452/ml_project/env
            git pull origin main
            jupyter nbconvert --to script /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/notebooks/training_gradient_boosting.ipynb --output-dir /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts
            python /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts/training_gradient_boosting.py

            
  testing:
    needs: [train_gradient_boosting]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 200m
          script: |
            source ~/.bashrc
            cd /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator
            conda activate /home/e19452/ml_project/env
            # jupyter nbconvert --to script /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/notebooks/testing.ipynb --output-dir /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts
            python /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/scripts/testing.py
            git checkout main
            git pull
            git add .
            git commit -m "Automated gradient boosting script update"
            # Configure git to use the PAT
            git config --global user.name "${{ secrets.GH_USERNAME }}"
            git config --global user.password "${{ secrets.GH_PAT}}"
            git push https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PAT }}@github.com/cepdnaclk/e19-co544-Diabetes-Health-Indicator.git main

  deploy_backend:
      # The type of runner that the job will run on
      needs: [testing]
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:       
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME_AH }}
          key: ${{ secrets.SSH_PRIVATE_KEY_AH }}
          port: 22
          script: |
            ssh -V
            cd /home/e19300/CO544/CO544-Flask-Backend
            rm -r __pycache__
            rm -r models/*
            mkdir models
            git checkout main
            git pull origin main
            source ~/.bashrc
            conda deactivate
            conda activate /home/e19300//miniconda3/envs/flaskApp/
            cp -rv /home/e19452/ml_project/e19-co544-Diabetes-Health-Indicator/models/* /home/e19300/CO544/CO544-Flask-Backend/models
            nohup gunicorn --bind 0.0.0.0:8888 wsgi:app &
            disown
